### ISSUE TITLE
pocketsnack authorise problem

### ISSUE THREAD

**Issue by lissertations** [hughrun/pocket-snack#18]
I copied the consumer key to `settings.py` as instructed, and when running `bash install.sh` I select '1' at 'Do you want to authorise your app now' but I get this error instead of a browser popup:
```
Authorise pocketsnack in the browser window that opens in a moment, then return to this command line to finish setting up.
Traceback (most recent call last):
  File "/usr/local/bin/pocketsnack", line 48, in <module>
    settings.pocket_access_token, 
AttributeError: module 'settings' has no attribute 'pocket_access_token'
```
And I'm like 'I know, you're meant to authorise me and add the access token to `settings.py`' but it's not doing that. Running `pocketsnack authorise` manually returns the same error.

**Comment by hughrun** [comment]
As discussed elsewhere, it looks like `pocket_access_token` needs to be in the default settings.py file for `pocketsnack x` to work, because it's referenced in the refresh_settings dict.

Will update this, and possibly change the install.sh script so it overwrites that line rather than appending.
