### ISSUE TITLE
pocketsnack everything problem

### ISSUE THREAD

**Issue by lissertations** [hughrun/pocket-snack#19]
- Downloaded pocket-snack.zip
- Copied (yes, copied, not renamed) `settings-example.py` to `settings.py` 
- Added the consumer key where it says to
- Opened terminal, ran `bash install.sh`
- Got the following output
```
Saorsa:pocket-snack-master Alissa$ bash install.sh
Making executable..
Linking to local binary directory..
ln: /usr/local/bin/pocketsnack: File exists
checking for Python3...
Python 3 is installed and python3 command works
Installation complete ✅ You can now get started!
-------------------------------------------------
Do you want to authorise your app with Pocket now? Choose 1 for Yes or 2 for No
1) Yes
2) No
#? 1
Authorise pocketsnack in the browser window that opens in a moment, then return to this command line to finish setting up.
install.sh: line 19: pocketsnack: command not found
Do you want to automatically refresh your Pocket List? This will run "stash" and then "lucky_dip" once per day, or once per week.
1) No Thanks
2) Yes Daily
3) Yes Weekly
#? 
```
Again, no browser window pops up to run `pocketsnack authorise`. You will note this error differs from #18 in that now pocketsnack suddenly doesn't exist at all, despite the code literally not changing.

I'm totally stumped at how the exact same code can produce two totally different errors. Happy Sunday!

**Comment by hughrun** [comment]
As discussed out of band, this was due partially to #18 but also to a problem with @lissertations symlink in /usr/local/bin/pocketsnack. I'm leaving this here as there should be documentation about how to clean this up if you reinstall in a new directory.
