### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by lissertations** [hughrun/pocket-snack#8]
The readme suggested I run `main.py`, so I did that without editing anything but including the `stash` argument, and got the following error
```
Saorsa:pocket-snack-master Alissa$ python3 main.py stash
Traceback (most recent call last): 
  File "main.py", line 37, in <module> 
    import settings 
ModuleNotFoundError: No module named 'settings'
```
Thinking this was because the settings file was actually named `settings-example.py`, I renamed it `settings.py` in case that did anything, but got this error instead
```
Saorsa:pocket-snack-master Alissa$ python3 main.py stash
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    stash = pt.stash(consumer_key, settings.pocket_access_token, archive_tag, settings.replace_all_tags, settings.retain_tags, settings.ignore_faves, settings.ignore_tags)
AttributeError: module 'settings' has no attribute 'pocket_access_token'
```

Which is weird because it clearly specifies `settings.pocket_access_token` ???

**Comment by hughrun** [comment]
Yep, correct you need to change settings-example.py to settings.py, but then run `python3 main.py authorise` before anything else.

**Comment by hughrun** [comment]
Make sure you have followed the instructions under "Creating an app in Pocket" - sounds like you haven't got a value for `pocket_consumer_key` Obviously I need to make the README instructions a bit easier to follow!

**Comment by hughrun** [comment]
This should hopefully be resolved with better instructions and a new line before adding the pocket token, in [v1.0.1](https://github.com/hughrun/pocket-snack/releases/tag/v1.0.1)
